#!/usr/bin/env python3
"""
Compute PANTHERM metrics from CoMeT epoch traces.

Inputs per run directory (generated by memTherm_core.py):
  - combined_instruction.trace      : per-core instruction deltas per epoch
  - combined_thread_mapping.trace   : per-core running thread id per epoch
  - combined_thread_weight.trace    : per-core running CFS weight per epoch

Metrics:
  1) Priority-Weighted Utility U
  2) Jain's Fairness Index J using r_i = NT_i / w_i
"""

import argparse
import math
import os
import re
from collections import defaultdict

IDLE_UNSIGNED_THRESHOLD = 9000000000000000000


def read_trace_rows(path):
    if not os.path.exists(path):
        raise FileNotFoundError("Required trace not found: %s" % path)

    with open(path, "r", encoding="utf-8") as f:
        lines = [ln.strip() for ln in f if ln.strip()]

    if not lines:
        raise ValueError("Trace file is empty: %s" % path)

    header = [tok for tok in lines[0].split("\t") if tok != ""]
    rows = []
    for ln in lines[1:]:
        toks = [tok for tok in ln.split("\t") if tok != ""]
        rows.append(toks)

    return header, rows


def parse_sim_cfg_sampling_interval_ns(sim_cfg_path):
    if not os.path.exists(sim_cfg_path):
        return None

    pattern = re.compile(r"^\s*sampling_interval\s*=\s*([0-9]+)")
    with open(sim_cfg_path, "r", encoding="utf-8", errors="ignore") as f:
        for ln in f:
            m = pattern.match(ln)
            if m:
                return int(m.group(1))
    return None


def normalize_thread_id(raw):
    if raw is None or raw == "":
        return -1
    tid = int(float(raw))
    if tid > IDLE_UNSIGNED_THRESHOLD:
        return -1
    return tid


def load_run_data(run_dir, instr_name, map_name, weight_name):
    instr_path = os.path.join(run_dir, instr_name)
    map_path = os.path.join(run_dir, map_name)
    weight_path = os.path.join(run_dir, weight_name)

    header_i, rows_i = read_trace_rows(instr_path)
    header_m, rows_m = read_trace_rows(map_path)
    header_w, rows_w = read_trace_rows(weight_path)

    if header_i != header_m or header_i != header_w:
        raise ValueError("Trace headers mismatch in run dir: %s" % run_dir)

    if not (len(rows_i) == len(rows_m) == len(rows_w)):
        raise ValueError("Trace row count mismatch in run dir: %s" % run_dir)

    ncores = len(header_i)
    nepochs = len(rows_i)

    thread_instr = defaultdict(float)
    thread_slots = defaultdict(int)
    thread_weights = defaultdict(list)

    total_active_slots = 0

    for e in range(nepochs):
        row_i = rows_i[e]
        row_m = rows_m[e]
        row_w = rows_w[e]

        if not (len(row_i) == len(row_m) == len(row_w) == ncores):
            raise ValueError("Column mismatch at epoch %d in %s" % (e, run_dir))

        for c in range(ncores):
            instr = float(row_i[c])
            tid = normalize_thread_id(row_m[c])
            w = float(row_w[c])

            if tid >= 0:
                thread_instr[tid] += instr
                thread_slots[tid] += 1
                total_active_slots += 1
                if w > 0.0:
                    thread_weights[tid].append(w)

    return {
        "ncores": ncores,
        "nepochs": nepochs,
        "thread_instr": dict(thread_instr),
        "thread_slots": dict(thread_slots),
        "thread_weights": dict(thread_weights),
        "total_active_slots": total_active_slots,
    }


def median(values):
    if not values:
        return 0.0
    s = sorted(values)
    k = len(s)
    m = k // 2
    if k % 2 == 1:
        return float(s[m])
    return 0.5 * (float(s[m - 1]) + float(s[m]))


def compute_per_thread_metrics(actual_data, ideal_data, total_time_sec):
    tids = sorted(set(actual_data["thread_instr"].keys()) | set(ideal_data["thread_instr"].keys()))

    total_active_slots = actual_data["total_active_slots"]
    if total_active_slots <= 0:
        raise ValueError("No active thread slots found in actual run.")

    result = []

    for tid in tids:
        instr_actual = float(actual_data["thread_instr"].get(tid, 0.0))
        instr_ideal = float(ideal_data["thread_instr"].get(tid, 0.0))

        ips_actual = instr_actual / total_time_sec if total_time_sec > 0 else 0.0
        ips_ideal = instr_ideal / total_time_sec if total_time_sec > 0 else 0.0

        nt = (ips_actual / ips_ideal) if ips_ideal > 0 else 0.0

        slots = int(actual_data["thread_slots"].get(tid, 0))
        w_i = float(slots) / float(total_active_slots)

        observed_weights = actual_data["thread_weights"].get(tid, [])
        w_priority = median(observed_weights)

        r_i = (nt / w_i) if w_i > 0 else 0.0

        result.append({
            "tid": tid,
            "instr_actual": instr_actual,
            "instr_ideal": instr_ideal,
            "ips_actual": ips_actual,
            "ips_ideal": ips_ideal,
            "nt": nt,
            "slots": slots,
            "w_i": w_i,
            "w_priority": w_priority,
            "r_i": r_i,
            "u_term": w_priority * ips_actual,
        })

    return result


def compute_u(per_thread):
    return sum(x["u_term"] for x in per_thread)


def compute_jain(per_thread):
    n = len(per_thread)
    if n == 0:
        return 0.0, 0.0, 0.0
    r_sum = sum(x["r_i"] for x in per_thread)
    r_sq_sum = sum(x["r_i"] * x["r_i"] for x in per_thread)
    numerator = r_sum * r_sum
    denominator = float(n) * r_sq_sum
    j = (numerator / denominator) if denominator > 0 else 0.0
    return j, numerator, denominator


def print_table(per_thread):
    cols = [
        "tid", "instr_actual", "instr_ideal", "IPS_actual", "IPS_ideal",
        "NT_i", "slots", "w_i", "W_priority_i", "r_i", "W_priority_i*IPS_actual"
    ]
    print("\nIntermediate per-thread values")
    print(" | ".join(cols))
    print("-" * 180)
    for x in per_thread:
        print(
            "%d | %.0f | %.0f | %.6f | %.6f | %.6f | %d | %.6f | %.6f | %.6f | %.6f" % (
                x["tid"],
                x["instr_actual"],
                x["instr_ideal"],
                x["ips_actual"],
                x["ips_ideal"],
                x["nt"],
                x["slots"],
                x["w_i"],
                x["w_priority"],
                x["r_i"],
                x["u_term"],
            )
        )


def build_arg_parser():
    p = argparse.ArgumentParser(description="Compute PANTHERM metrics from CoMeT traces")
    p.add_argument("--actual-dir", required=True, help="Run directory for PANTHERM (thermal-managed) run")
    p.add_argument("--ideal-dir", required=True, help="Run directory for ideal run (max freq, no thermal throttling)")
    p.add_argument("--baseline-dir", default=None, help="Optional naive-DTM run directory for %%U comparison")
    p.add_argument("--sampling-interval-ns", type=int, default=None,
                   help="Epoch duration in ns. If omitted, read from actual-dir/sim.cfg")
    p.add_argument("--instruction-trace", default="combined_instruction.trace")
    p.add_argument("--mapping-trace", default="combined_thread_mapping.trace")
    p.add_argument("--weight-trace", default="combined_thread_weight.trace")
    return p


def main():
    args = build_arg_parser().parse_args()

    sampling_interval_ns = args.sampling_interval_ns
    if sampling_interval_ns is None:
        sampling_interval_ns = parse_sim_cfg_sampling_interval_ns(os.path.join(args.actual_dir, "sim.cfg"))
    if sampling_interval_ns is None:
        raise ValueError("Could not infer sampling interval. Pass --sampling-interval-ns explicitly.")

    actual_data = load_run_data(args.actual_dir, args.instruction_trace, args.mapping_trace, args.weight_trace)
    ideal_data = load_run_data(args.ideal_dir, args.instruction_trace, args.mapping_trace, args.weight_trace)

    if actual_data["nepochs"] != ideal_data["nepochs"]:
        print("Warning: actual and ideal epoch counts differ (%d vs %d)." % (
            actual_data["nepochs"], ideal_data["nepochs"]
        ))

    total_time_sec = actual_data["nepochs"] * sampling_interval_ns * 1e-9

    print("Data extraction summary")
    print("actual_dir = %s" % args.actual_dir)
    print("ideal_dir = %s" % args.ideal_dir)
    print("epochs = %d" % actual_data["nepochs"])
    print("cores = %d" % actual_data["ncores"])
    print("sampling_interval_ns = %d" % sampling_interval_ns)
    print("total_time_sec = epochs * sampling_interval_ns * 1e-9 = %d * %d * 1e-9 = %.9f" % (
        actual_data["nepochs"], sampling_interval_ns, total_time_sec
    ))

    per_thread = compute_per_thread_metrics(actual_data, ideal_data, total_time_sec)
    print_table(per_thread)

    n = len(per_thread)
    U = compute_u(per_thread)
    J, numerator, denominator = compute_jain(per_thread)

    print("\nStep-by-step Metric 1: Priority-Weighted Utility U")
    print("U = sum_i(W_priority_i * IPS_actual_i)")
    for x in per_thread:
        print("  thread %d: %.6f * %.6f = %.6f" % (
            x["tid"], x["w_priority"], x["ips_actual"], x["u_term"]
        ))
    print("U = %.6f" % U)

    baseline_u = None
    if args.baseline_dir:
        baseline_data = load_run_data(args.baseline_dir, args.instruction_trace, args.mapping_trace, args.weight_trace)
        baseline_per_thread = compute_per_thread_metrics(baseline_data, ideal_data, total_time_sec)
        baseline_u = compute_u(baseline_per_thread)
        delta_u = ((U - baseline_u) / baseline_u * 100.0) if baseline_u != 0 else math.nan
        print("baseline_dir = %s" % args.baseline_dir)
        print("U_baseline = %.6f" % baseline_u)
        print("%% change vs baseline = ((U - U_baseline) / U_baseline) * 100 = %.6f%%" % delta_u)

    print("\nStep-by-step Metric 2: Jain's Fairness Index J")
    print("For each thread: r_i = NT_i / w_i")
    for x in per_thread:
        print("  thread %d: r_i = %.6f / %.6f = %.6f" % (
            x["tid"], x["nt"], x["w_i"], x["r_i"]
        ))

    r_sum = sum(x["r_i"] for x in per_thread)
    r_sq_sum = sum(x["r_i"] * x["r_i"] for x in per_thread)

    print("numerator = (sum r_i)^2 = (%.6f)^2 = %.6f" % (r_sum, numerator))
    print("denominator = n * sum(r_i^2) = %d * %.6f = %.6f" % (n, r_sq_sum, denominator))
    print("J = numerator / denominator = %.6f / %.6f = %.4f" % (numerator, denominator, J))


if __name__ == "__main__":
    main()
